# Generated by Django 5.0.6 on 2024-08-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
