# Generated by Django 5.0.6 on 2024-08-22 19:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_entrega_confirmada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='confirmada',
            new_name='confirmado',
        ),
        migrations.AddField(
            model_name='entrega',
            name='token_confirmacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
